GET http://localhost:8000/hello

###
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "asdajskj",
    "password": "sdnklxnflsdn"
}

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name":" Nameee",
    "email": "asdajskj",
    "password": "sdnklxnflsdn"
}
 
