GET http://localhost:8000/hello

###
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "4@dfsdf.tu",
    "password": "sdf1"
}

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name":"sdfsd",
    "email": "4@dfsdf.tu",
    "password": "sdf"
}
