@startuml
Пользователь --> (Использование приложения) #line:red;line.bold;text:red  : Данные о товаре 
(Использование приложения) --> Пользователь : Код
Вася --> (Использование приложения) : Данные о товаре
(Использование приложения) --> Вася : Код
Петя --> (Использование приложения) : Данные о товаре
(Использование приложения) --> Петя: Код
Интернетмагазин --> (Использование приложения) : Данные о товаре
(Использование приложения) --> Интернетмагазин : Код
:Главный админ: --> (Использование приложения) : Еще одна\nнебольшая\nзаметка
(Использование приложения) --> :Главный админ:  : Еще одна\nнебольшая\nзаметка
@enduml
