@startuml
scale 750 width
skinparam componentStyle rectangle

[Склад] as WMS

Пользователь -down-> WMS #line:red;line.bold;text:red  : Данные о товаре 
WMS -up-> Пользователь : Код
Вася --> WMS : Данные о товаре
WMS --> Вася : Код
[Delivery Service] -left-> WMS : Данные о товаре
WMS -right-> [Delivery Service] : Код
[Интернет-магазин] -right-> WMS : Данные о товаре
WMS -left-> [Интернет-магазин] : Код

:Главный админ: -down-> WMS : Еще одна\nнебольшая\nзаметка
WMS -up-> :Главный админ:  : Еще одна\nнебольшая\nзаметка
@enduml
