@startmindmap

+ Команда бизнес-аналитиков
++ Сбор и анализ бизнес-требований
+++ Реестр BReq and BRules готовы

+ Команда системных-аналитиков
++ Определение требований
+++ Анализ потоков данных
++++ Контекстная диаграмма готова
+++ Разработка вариантов использования
++++ Реест системным Use cases готов
+++ Моделирование предметной области
++++ Модель предметной области готова
+++ Разработка детальных Use cases
++++ Use cases готовы

+ Проектирование
++ Проектирование БД
+++ Проектирование БД завершено
++ Разработка диаграмм последовательности
+++ Диаграммы последовательности готовы
++ Проектирование REST API
+++ Описание REST API готово

+ Команда разработки
++ Развертывание инфраструктуры проекта
++ Настройка Sensible defaults
+++ Инфраструктура проекта готова
++ Разработка схемы БД (prisma schema)
+++ Схема БД готова
++ Разработка слоя бизнес-логики
+++ Слой бизнес-логики готов
++ Разработка unit tests
+++ Unit-tests готовы
++ Разработка слоя контроллера
+++ Слой контроллера готов
++ Разработка слоя репозитория
+++ Слой репозитория готов
++ Разворачивание приложения на сервер
+++ Приложение на сервере

+ Команда тестирования
++ Разработка e2e tests
+++ e2e test готовы
++ Тестирование приложения
+++ Приложение готово в прод

@endmindmap
