@startgantt

-- Команда бизнес-аналитиков --
[Разработка бизнес-требований] as [BA] lasts 13 days

-- Команда системных-аналитиков --
[Определение требований] as [SA1] lasts 11 days
[SA1] starts after [BA]'s end
[Проектирование] as [SA2] lasts 8 days
[SA2] starts after [SA1]'s end

-- Команда разработки --
[Разработка] as [Dev] lasts 11 days
[Dev] starts after [SA2]'s end
[Разворачивание приложения на сервер] as [Deploy] lasts 2 days
[Deploy] starts after [Dev]'s end

-- Команда тестирования --
[Разработка e2e tests] as [Testing1] lasts 9 days
[Testing1] starts after [Deploy]'s end

[Тестирование приложения] as [Testing2] lasts 3 days
[Testing2] starts after [Testing1]'s end

-- Команда Devops --
[Релиз] as [ProdRelease] lasts 3 days
[ProdRelease] starts after [Testing2]'s end

@endgantt


