@startgantt
language ru
-- Команда бизнес-аналитиков --
[Сбор и анализ бизнес-требований] lasts 13 days
[Реестр BReq and BRules готовы] happens at [Сбор и анализ бизнес-требований]'s end

-- Команда системных-аналитиков --
-- Определение требований --

[Анализ потоков данных] lasts 11 days
[Анализ потоков данных] starts at [Сбор и анализ бизнес-требований]'s end
[Контекстная диаграмма готова] happens at [Анализ потоков данных]'s end

[Разработка вариантов использования] starts at [Сбор и анализ бизнес-требований]'s end
[Разработка вариантов использования] lasts 11 days
[Реест системным Use cases готов] happens at [Разработка вариантов использования]'s end

[Моделирование предметной области] starts at [Сбор и анализ бизнес-требований]'s end
[Моделирование предметной области] lasts 11 days
[Модель предметной области готова] happens at [Моделирование предметной области]'s end

[Разработка детальных Use cases] starts at [Сбор и анализ бизнес-требований]'s end
[Разработка детальных Use cases] lasts 11 days
[Use cases готовы] happens at [Разработка детальных Use cases]'s end

-- Проектирование --

[Проектирование БД] starts at [Моделирование предметной области]'s end
[Проектирование БД] lasts 8 days
[Проектирование БД завершено] happens at [Проектирование БД]'s end

[Разработка диаграмм последовательности] starts at [Анализ потоков данных]'s end
[Разработка диаграмм последовательности] starts at [Разработка вариантов использования]'s end
[Разработка диаграмм последовательности] starts at [Моделирование предметной области]'s end
[Разработка диаграмм последовательности] starts at [Разработка детальных Use cases]'s end
[Разработка диаграмм последовательности] lasts 8 days
[Диаграммы последовательности готовы] happens at [Разработка диаграмм последовательности]'s end

[Проектирование REST API] starts at [Разработка детальных Use cases]'s end
[Проектирование REST API] lasts 8 days
[Описание REST API готово] happens at [Проектирование REST API]'s end


-- Команда разработки --

[Развертывание инфраструктуры проекта] lasts 3 days

[Настройка Sensible defaults] starts at [Развертывание инфраструктуры проекта]'s end
[Настройка Sensible defaults] lasts 4 days
[Инфраструктура проекта готова] happens at [Настройка Sensible defaults]'s end

[Разработка схемы БД (prisma schema)] starts at [Проектирование БД]'s end
[Разработка схемы БД (prisma schema)] starts at [Настройка Sensible defaults]'s end
[Разработка схемы БД (prisma schema)] lasts 4 days
[Схема БД готова] happens at [Разработка схемы БД (prisma schema)]'s end

[Разработка слоя бизнес-логики] starts at [Разработка диаграмм последовательности]'s end
[Разработка слоя бизнес-логики] lasts 4 days
[Слой бизнес-логики готов] happens at [Разработка слоя бизнес-логики]'s end

[Разработка unit tests] starts at [Разработка слоя бизнес-логики]'s end
[Разработка unit tests] lasts 4 days
[Unit-tests готовы] happens at [Разработка unit tests]'s end

[Разработка слоя контроллера] starts at [Проектирование REST API]'s end
[Разработка слоя контроллера] lasts 4 days
[Слой контроллера готов] happens at [Разработка слоя контроллера]'s end

[Разработка слоя репозитория] starts at [Разработка схемы БД (prisma schema)]'s end
[Разработка слоя репозитория] lasts 4 days
[Слой репозитория готов] happens at [Разработка слоя репозитория]'s end

[Разворачивание приложения на сервер] starts at [Разработка слоя репозитория]'s end
[Разворачивание приложения на сервер] starts at [Разработка слоя контроллера]'s end
[Разворачивание приложения на сервер] starts at [Разработка unit tests]'s end

[Разворачивание приложения на сервер] lasts 4 days
[Приложение на сервере] happens at [Разворачивание приложения на сервер]'s end
-- Команда тестирования --


[Разработка e2e tests] starts at [Разработка слоя контроллера]'s end
[Разработка e2e tests] lasts 4 days
[e2e test готовы] happens at [Разработка e2e tests]'s end

[Тестирование приложения] starts at [Разворачивание приложения на сервер]'s end
[Тестирование приложения] starts at [Разработка e2e tests]'s end
[Тестирование приложения] lasts 4 days
[Приложение готово в прод] happens at [Тестирование приложения]'s end
@endgantt
