@startuml
skinparam minClassWidth 125
skinparam nodesep 10
skinparam ranksep 10

title "Cуществующее решение"

rectangle "Слой приложений" {
rectangle Mirapolis as MP   #Application 
rectangle УчиПро as UPR #Application 
rectangle Сбербанк as SBRPAY #Application
rectangle "Сайт. \nВитрина программ обучения" as SITE  #Application
}

rectangle "Слой бизнес-процессов" {
rectangle "Заочные уроки" as OFFLINE #Business 
rectangle "Вебинары" as WEBINAR #Business 
rectangle "Платеж" as PAY #Business 
rectangle "Выбор Программы обучения" as EDUPROG #Business
}

EDUPROG ...-Right....>  PAY 
PAY ....-Right...>  WEBINAR
WEBINAR ....-Right...>  OFFLINE : Перевод записи \n на другую платформу
MP ....-Right...>  UPR: Перевод записи \n на другую платформу

EDUPROG <.......> SITE  
PAY <.......> SBRPAY
OFFLINE <.......> UPR 
WEBINAR <.......> MP


legend left
    |Color| Type |
    |<#FEFECE>| Бизнес-процесс|
    |<#A9DCDF>| Приложение|
endlegend
@enduml
