@startuml
skin rose
left to right direction

title Варианты использование системы 

:Слушатель: as STUDENT
:Преподаватель: as LECTOR
:Методист: as METOD
:Контент-менеджер: as CONTMGR
:Менеджер по продажам курсов: as MGR
:Администратор \nсистемы: as ADMIN

[Платежные системы] as Payments
[Бухгалтерия] as Commercia

rectangle  :Платформа: {

usecase (Обучение) as UC1
usecase (Приемка практических \n работ Слушателей) as UC2
usecase (Просмотр списка слушатей,\n отчетов об успеваемости) as UC3
usecase (Управление контентом) as UC4
usecase (Продажа курсов и\nработа с клиентами) as UC5

usecase (Управление пользователями \nи группами доступа) as UC7
usecase (Техническая поддержка) as UC8
}

STUDENT --> UC1
LECTOR --> UC2
METOD--> UC3
CONTMGR--> UC4
MGR --> UC5

UC5 --> Payments
UC5 --> Commercia

ADMIN --> UC7
ADMIN --> UC8

@enduml
